//------------------------------------------------------------------------------
// <auto-generated>
//     This Code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the Code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinguin_Clone {
    
    
    public partial class _Default {
        
        /// <summary>
        /// jumbotron control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl jumbotron;
        
        /// <summary>
        /// imgJumbotron control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Image imgJumbotron;
    }
}
