//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinguin_Clone {
    
    
    public partial class Login {
        
        /// <summary>
        /// LoginForm control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Login LoginForm;
        
        /// <summary>
        /// hlRegister control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hlRegister;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SiteMaster Master {
            get {
                return ((SiteMaster)(base.Master));
            }
        }
    }
}
