//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace kinguin_Clone {
    
    
    public partial class Register {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new kinguin_Clone.SiteMaster Master {
            get {
                return ((kinguin_Clone.SiteMaster)(base.Master));
            }
        }
    }
}
