//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Kinguin_Clone {
    
    
    public partial class UserPage {
        
        /// <summary>
        /// lblName control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblName;
        
        /// <summary>
        /// lblAdres control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblAdres;
        
        /// <summary>
        /// lblPhonenr control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblPhonenr;
        
        /// <summary>
        /// lblKinguinBalance control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Label lblKinguinBalance;
        
        /// <summary>
        /// hlChangeUserinfo control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hlChangeUserinfo;
        
        /// <summary>
        /// hlAddGame control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hlAddGame;
        
        /// <summary>
        /// hlAddObject control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to Code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HyperLink hlAddObject;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new SiteMaster Master {
            get {
                return ((SiteMaster)(base.Master));
            }
        }
    }
}
